### ISSUE TITLE
can not find ./parser/index

### ISSUE THREAD

**Issue by luohongliang-o** [HSunboy/cuopyue#1]
when i use import {parser}  from "cuopyue",there report  Cannot find module './parser/index'.how did i do with these?please help me. thanks

**Comment by HSunboy** [comment]
https://codesandbox.io/s/unruffled-lovelace-ytsxv?file=/src/App.js
This online example works fine.
I don't think this is the problem of cuopyue, so please check your project configuration.

**Comment by luohongliang-o** [comment]
I use this project with vue,not react
